name: personality_test_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2 # 현재 사용 중인 SDK 버전

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  intl: ^0.18.1
  http: ^1.2.0
  url_launcher: ^6.2.5
  google_mobile_ads: ^6.0.0
  share_plus: ^7.2.2
  mockito: ^5.4.4

  flutter_lints: ^4.0.0
  firebase_core: ^2.32.0
  firebase_analytics: ^10.8.4
  firebase_remote_config: ^4.4.7
  firebase_database: ^10.5.5
  firebase_auth: ^4.20.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - res/api/